[package]
name = "sopho"
version = "0.1.0"
authors = ["Cyryl Płotnicki <cyplo@cyplo.net>"]
edition = "2018"

[dependencies]
structopt = "0.3"
walkdir = "2.3"
rexif = "0.5"
anyhow = "1.0"
chrono = "0.4"
rayon = "1.3"